const LIBRARY = [
{
  id: "p-442347",
  name: "two doubles",
  theme: "warehouse",
  map: [
    "wwwwsww",
    "w_____w",
    "ww_wcww",
    "w_c_c_w",
    "wwcw_ww",
    "w_____w",
    "wwfwwww",
  ],
  under: {},
  meta: { dir: "both", rating: 2, sf: 3, fs: 3, sfs: true, fsf: true, parts: "c" },
},
{
  id: "p-190bc7",
  name: "crate in my door",
  theme: "warehouse",
  map: [
    "wwswwww",
    "w_____w",
    "w_w_w_w",
    "w-=c=-w",
    "ww___ww",
    "ww_w_ww",
    "ww___ww",
    "wwwfwww",
  ],
  under: {"3,3":"-"},
  meta: { dir: "sf", rating: 1, sf: 1, fs: null, sfs: true, fsf: false, parts: "-=c" },
},
{
  id: "p-07a9f7",
  name: "a mess",
  theme: "warehouse",
  map: [
    "wwwswww",
    "w___c_w",
    "wc_c_cw",
    "w_cc_cw",
    "w__cccw",
    "w_c_c_w",
    "wwwfwww",
  ],
  under: {},
  meta: { dir: "both", rating: 2, sf: 3, fs: 2, sfs: true, fsf: true, parts: "c" },
},
{
  id: "p-77594d",
  name: "sliding door",
  theme: "warehouse",
  map: [
    "wwwswww",
    "w_____w",
    "oc===co",
    "w_w_w_w",
    "wwwfwww",
  ],
  under: {"1,2":"-","5,2":"-"},
  meta: { dir: "sf", rating: 2, sf: 4, fs: null, sfs: true, fsf: false, parts: "-=co" },
},
{
  id: "p-75e29b",
  name: "feeling cross",
  theme: "warehouse",
  map: [
    "wwwswww",
    "w_____w",
    "wccc__w",
    "wcc║=_w",
    "w_co_ww",
    "w__w_fw",
    "wwwwwww",
  ],
  under: {"1,3":"-","2,3":"-","3,3":"+"},
  meta: { dir: "sf", rating: 2, sf: 4, fs: null, sfs: true, fsf: false, parts: "+-=co║" },
},
{
  id: "p-7d71c5",
  name: "storeroom",
  theme: "warehouse",
  map: [
    "wwwswww",
    "w_c___w",
    "wc_cc_w",
    "w-c=--w",
    "f_ccccw",
    "w__cccw",
    "wwwwwww",
  ],
  under: {"2,3":"-"},
  meta: { dir: "both", rating: 2, sf: 2, fs: 2, sfs: true, fsf: true, parts: "-=c" },
},
{
  id: "p-fcb405",
  name: "how hard",
  theme: "warehouse",
  map: [
    "wswwwfw",
    "o-===-o",
    "w__ww_w",
    "o-==--o",
    "ww_w__w",
    "o--==-o",
    "wwwwwww",
  ],
  under: {},
  meta: { dir: "both", rating: 2, sf: 3, fs: 2, sfs: true, fsf: true, parts: "-=o" },
},
{
  id: "p-119620",
  name: "go back",
  theme: "warehouse",
  map: [
    "wwwfow",
    "www_|w",
    "w__=║w",
    "s_w_║w",
    "w_ww_w",
    "w____w",
    "wwwwww",
  ],
  under: {"4,2":"+"},
  meta: { dir: "sf", rating: 1, sf: 3, fs: null, sfs: true, fsf: false, parts: "+-=o|║" },
},
{
  id: "p-46a361",
  name: "tiny",
  theme: "warehouse",
  map: [
    "wwfww",
    "ww__w",
    "w_ccw",
    "s___w",
    "wwwww",
  ],
  under: {},
  meta: { dir: "both", rating: 1, sf: 2, fs: 1, sfs: true, fsf: true, parts: "c" },
},
{
  id: "p-90f80e",
  name: "easy parking",
  theme: "warehouse",
  map: [
    "wwwwww",
    "w_==-w",
    "w_║www",
    "s_║_fw",
    "w║|║_w",
    "w|||ww",
    "wwwwww",
  ],
  under: {"2,1":"+"},
  meta: { dir: "sf", rating: 1, sf: 3, fs: null, sfs: true, fsf: false, parts: "+-=|║" },
},
{
  id: "p-e11da7",
  name: "jammed",
  theme: "warehouse",
  map: [
    "wwwwwwwww",
    "w_______w",
    "w__w║|__w",
    "s___║|__w",
    "wccc==-_w",
    "w___|║www",
    "w__w|║__f",
    "w_____www",
    "wwwwwwwww",
  ],
  under: {"2,4":"-","3,4":"-","4,4":"+","5,4":"+"},
  meta: { dir: "sf", rating: 2, sf: 5, fs: null, sfs: true, fsf: false, parts: "+-=c|║" },
},
{
  id: "p-cffe9a",
  name: "billiards",
  theme: "cold",
  map: [
    "wwwwwwwwwwwwwww",
    "w~~~~~~~~~~~~~w",
    "w~~~~~~wcw~~~~w",
    "ww~~~~~~~~~w~~w",
    "w~~~~~~~~w~~~~w",
    "w~~~~~~~~~~~~~w",
    "w~~~~~~~~~~~~~w",
    "s~~~~~~w~~~c~~f",
    "w~w~~~~~~~c~~~w",
    "w~~~~~~~~~~~~cw",
    "w~~~~~w~~~~~~~w",
    "w~~~~~~~~w~~~~w",
    "w~~w~~~~~~~~~~w",
    "w~~~~~~~~~~~~~w",
    "wwwwwwwwwwwwwww",
  ],
  under: {"8,2":"~","11,7":"~","10,8":"~","13,9":"~"},
  meta: { dir: "both", rating: 2, sf: 3, fs: 2, sfs: true, fsf: true, parts: "c~" },
},
{
  id: "p-2c5247",
  name: "Swan lake",
  theme: "cold",
  map: [
    "wwwwwwwwwwwwwww",
    "wwwwwwww~~~~www",
    "wwww~~~~~~~~~ww",
    "ww~~~~~~~~~~~ww",
    "ww~~~~~w~~~wwww",
    "w~~~~~~~~~~~www",
    "w~~~~~w~~~~~~~w",
    "s~~~~www~~~~~~f",
    "ww~~~~w~~~~~~ww",
    "ww~~~~~~~~~~~ww",
    "ww~~~~~~~~~~~ww",
    "www~~~~~~~~~www",
    "wwww~~~~~wwwwww",
    "wwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwww",
  ],
  under: {},
  meta: { dir: "both", rating: 0, sf: 0, fs: 0, sfs: true, fsf: true, parts: "~" },
},
{
  id: "p-8a98c9",
  name: "Kiddie slide",
  theme: "cold",
  map: [
    "wwwwww",
    "w~~~~w",
    "wc~~~f",
    "s~~~~w",
    "w~~~~w",
    "wwwwww",
  ],
  under: {"1,2":"~"},
  meta: { dir: "both", rating: 1, sf: 1, fs: 1, sfs: true, fsf: true, parts: "c~" },
},
{
  id: "p-f82b87",
  name: "careful pond",
  theme: "warehouse",
  map: [
    "wwwwwwwwwwwwwww",
    "wwwwwww*~~wwwww",
    "wwww****~~~~~ww",
    "www*******~~~ww",
    "ww*********~~~w",
    "w__**www***~~~w",
    "w___*www~~~~~~w",
    "s___--=hh~~~~~f",
    "w_____ww~~~~~~w",
    "w______w~~~~~~w",
    "w________~~~~~w",
    "ww__w_____~~~ww",
    "ww_____w___~~ww",
    "www___www__~~ww",
    "wwwwwwwwwwwwwww",
  ],
  under: {"6,7":"h"},
  meta: { dir: "either-once", rating: 5, sf: 26, fs: 1, sfs: false, fsf: true, parts: "*-=h~", byPlayer: "sf" },
}
];
if (typeof module !== "undefined") module.exports = LIBRARY;
